apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
   - type: Container
      default:
        cpu: '1'
        memory: 1000Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
